service: lambda-papertrail

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    PAPERTRAIL_HOST: ${ssm:PAPERTRAIL_HOST}
    PAPERTRAIL_PORT: ${ssm:PAPERTRAIL_PORT}

functions:
  forwarder:
    handler: handler.log

resources:
  Resources:
    ForwarderLambdaPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName:
          Fn::GetAtt: [ForwarderLambdaFunction, Arn]
        Principal: logs.${self:provider.region}.amazonaws.com
  Outputs:
    ForwarderLambdaArn:
      Value:
        Fn::GetAtt: [ForwarderLambdaFunction, Arn]
